//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikayeWebApp.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHikayeEntities1 : DbContext
    {
        public DbHikayeEntities1()
            : base("name=DbHikayeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblHikayeler> TblHikayeler { get; set; }
        public virtual DbSet<TblKategoriler> TblKategoriler { get; set; }
        public virtual DbSet<TblKullanicilar> TblKullanicilar { get; set; }
    }
}
