//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikayeWebApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHikayeler
    {
        public int HikayeID { get; set; }
        public string HikayeBaslik { get; set; }
        public string HikayeIcerik { get; set; }
        public Nullable<byte> HikayeYazar { get; set; }
        public Nullable<byte> HikayeKategori { get; set; }
        public Nullable<System.DateTime> HikayeTarih { get; set; }
    
        public virtual TblKategoriler TblKategoriler { get; set; }
        public virtual TblKullanicilar TblKullanicilar { get; set; }
    }
}
